import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import DataImg from '../public/data.png'

export default function Home() {

  const router = useRouter()

  return (
    <div className='hero-section w-full'>
      <Head>
        <title>Unfraud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-full flex items-center p-32 gap-12' style={{height:"calc(100vh - 76px)"}} >
        <div className='w-2/5 ml-[7vw]'>
          <Image src={DataImg} alt="" />
        </div>
        <div className=''>
          <h1 className='text-8xl'>Unfraud</h1>
          <p className='text-xl text-[#ffffff8a]'>An AI-based application in detecting <br/> healthcare fraud claims</p>
          <button className="bg-[#0072F5] px-6 py-2.5 rounded-md mt-6" onClick={()=>router.push('/app')}>
            Go to app
          </button>
        </div>
      </div>
      
    </div>
  )
}
